const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../src/js/app.js'),'utf8');
const helpers=source.slice(source.indexOf('const goalsQueryCache ='),source.indexOf('async function renderGoalsView('));
const view=source.slice(source.indexOf('async function renderGoalsView('),source.indexOf('async function renderGoalsChart('));
function element(){return {dataset:{},attrs:{'aria-expanded':'false'},innerHTML:'',textContent:'',events:{},classes:new Set(),classList:{add(){},remove(){},toggle(){}},getAttribute(k){return this.attrs[k]},setAttribute(k,v){this.attrs[k]=v},addEventListener(k,v){this.events[k]=v}}}
function environment(){const nodes=new Map(['goals-details-toggle','goals-details-panel','goals-details-label','goals-details-chevron','goals-table-head','goals-table-body','goals-loading','goals-filter-ano','goals-filter-mes'].map(k=>[k,element()]));nodes.get('goals-filter-ano').value='2026';nodes.get('goals-filter-mes').value='10';let chartCalls=0;const pending=[];const ctx=vm.createContext({Promise,JSON,Map,Date,console:{error(){}},window:{goalsMultiFilters:{}},currentGoalsAno:2026,currentGoalsMes:10,document:{getElementById:k=>nodes.get(k)},renderGoalsChart(){chartCalls++;return new Promise(()=>{})},supabase:{rpc:(name,args)=>new Promise(resolve=>pending.push({name,args,resolve}))}});vm.runInContext(helpers+view,ctx);return {ctx,nodes,pending,chartCalls:()=>chartCalls}}
test('collapsed detail skips table queries; expanded table starts without waiting for chart',async()=>{const e=environment();await e.ctx.renderGoalsView();assert.equal(e.pending.length,0);assert.equal(e.chartCalls(),1);e.nodes.get('goals-details-toggle').setAttribute('aria-expanded','true');const job=e.ctx.renderGoalsView();assert.equal(e.pending.length,2);assert.equal(e.chartCalls(),2);e.pending.forEach(p=>p.resolve({error:new Error('test')}));await job;assert.match(e.nodes.get('goals-table-body').innerHTML,/Erro ao carregar/)});
test('toggle opens and closes once and exposes accessible state',async()=>{const e=environment();await e.ctx.renderGoalsView();const button=e.nodes.get('goals-details-toggle');button.events.click();assert.equal(button.getAttribute('aria-expanded'),'true');assert.equal(e.nodes.get('goals-details-label').textContent,'Ocultar tabela de metas detalhada');assert.equal(e.pending.length,2);button.events.click();assert.equal(button.getAttribute('aria-expanded'),'false');e.nodes.get('goals-table-body').innerHTML='current';e.pending.forEach(p=>p.resolve({error:new Error('old')}));await new Promise(setImmediate);assert.equal(e.nodes.get('goals-table-body').innerHTML,'current')});
test('query cache deduplicates sorted selections, retries failures and invalidates after saves',async()=>{const e=environment();const a=e.ctx.fetchGoalsQuery('read',{p_ano:2026,p_vendedores:['284','174']});const b=e.ctx.fetchGoalsQuery('read',{p_vendedores:['174','284'],p_ano:2026});assert.equal(a,b);assert.equal(e.pending.length,1);e.pending[0].resolve({data:{ok:true},error:null});await a;await e.ctx.fetchGoalsQuery('read',{p_ano:2026,p_vendedores:['284','174']});assert.equal(e.pending.length,1);e.ctx.clearGoalsQueryCache();const c=e.ctx.fetchGoalsQuery('read',{p_ano:2026,p_vendedores:['284','174']});e.pending[1].resolve({error:new Error('failed')});await c;const d=e.ctx.fetchGoalsQuery('read',{p_ano:2026,p_vendedores:['284','174']});assert.equal(e.pending.length,3);e.pending[2].resolve({data:{ok:true}});await d});
test('newer month keeps its loading and table state when an old request completes',async()=>{const e=environment();e.nodes.get('goals-details-toggle').setAttribute('aria-expanded','true');const old=e.ctx.renderGoalsView({tableOnly:true});e.nodes.get('goals-filter-mes').value='11';const latest=e.ctx.renderGoalsView({tableOnly:true});e.pending.slice(2).forEach(p=>p.resolve({error:new Error('new')}));await latest;e.nodes.get('goals-table-body').innerHTML='new month';e.pending.slice(0,2).forEach(p=>p.resolve({error:new Error('old')}));await old;assert.equal(e.nodes.get('goals-table-body').innerHTML,'new month')});
test('detail panel is hidden by default and cache is invalidated on each mutation',()=>{const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');assert.match(html,/<div id="goals-details-panel" class="hidden">/);assert.ok((source.match(/clearGoalsQueryCache\(\);/g)||[]).length>=4)});
